### ISSUE TITLE
callback twice fire after SocketAssignTimeoutError

### ISSUE THREAD

**Issue by fengmk2** [node-modules/urllib#227]
``` log
[urllib:warn] [Sun Oct 16 2016 16:43:01 GMT+0000 (UTC)] [worker:2893] GET https://registry.npmjs.com/pedding/latest callback twice!!!
[urllib:warn] [Sun Oct 16 2016 16:43:01 GMT+0000 (UTC)] [worker:2893] SocketAssignTimeoutError: Connect timeout for 60000ms, working sockets is full
stack: SocketAssignTimeoutError: Connect timeout for 60000ms, working sockets is full
    at Timeout._onTimeout (/home/travis/build/cnpm/npminstall/node_modules/urllib/lib/urllib.js:701:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[urllib:warn] [Sun Oct 16 2016 16:43:01 GMT+0000 (UTC)] [worker:2893] GET https://registry.npmjs.com/pedding/latest callback twice!!!
[urllib:warn] [Sun Oct 16 2016 16:43:01 GMT+0000 (UTC)] [worker:2893] SocketAssignTimeoutError: Connect timeout for 60000ms, working sockets is full
stack: SocketAssignTimeoutError: Connect timeout for 60000ms, working sockets is full
    at Timeout._onTimeout (/home/travis/build/cnpm/npminstall/node_modules/urllib/lib/urllib.js:701:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by arifeng** [comment]
+1 
When used with async it will cause program to crash with "uncaughtException: Callback was already called."

**Comment by alber1986** [comment]
is good very good

**Comment by littledu** [comment]
我在一个异步流程里下载资源，也偶现这个错误
大概代码：

```js
urllib.request(cdnUrl, options)
```

报错信息：
Error: SocketAssignTimeoutError: Connect timeout for 5000ms, working sockets is full

@fengmk2

**Comment by Lsnsh** [comment]
During concurrent requests, this warning appears when using `console.error` to output logs. When using `console.log` instead, the warning disappears.
