### ISSUE TITLE
ConnectionTimeoutError

### ISSUE THREAD

**Issue by modraedlau** [node-modules/urllib#317]
第一次接触egg，按官方的文档写hacker-news，发现urllib竟然报ConnectionTimeoutError，十分懊恼。我单独写了个js来测试，发现还是报错。我使用本机浏览器访问hancker-news的api是没有问题的，另外在命令行用curl也能正常访问，唯独使用urllib报timeout。我增加timeout的时间也无济于事。例子如下：
```
const urllib = require('urllib');

urllib.request('https://hacker-news.firebaseio.com/v0/topstories.json', {
  data: {
    orderBy: '"$key"',
    startAt: `"0"`,
    endAt: `"1"`,
  },
  dataType: 'json',
}, function(err, data, res) {
  if (err) {
    throw err; // you need to handle error
  }
  console.log(res.statusCode);
  console.log(res.headers);
  // data is Buffer instance
  console.log(data.toString());
});
```
错误信息：
```
ConnectionTimeoutError: Connect timeout for 5000ms, GET https://hacker-news.firebaseio.com/v0/topstories.json -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Timeout._onTimeout (/Users/***/Projects/egg/urllib-test/node_modules/urllib/lib/urllib.js:855:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

本机的环境：
操作系统：macOS Mojave (版本10.14.4)
shell: zsh
node版本：v8.16.0
urllib版本：2.33.3

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/57271283-7aa2cf00-70c1-11e9-893a-375685e6ebe4.png)

你的运行环境网络问题吧，urllib 不会走系统翻墙配置的。

**Comment by fengmk2** [comment]
@atian25 egg 的示例不应该走 hack news，网络不稳定。

**Comment by atian25** [comment]
Chair 新文档已经改为 todomvc 了，还没下沉出来。

现在的话可以考虑加代理：https://eggjs.org/zh-cn/core/httpclient.html#%E8%B0%83%E8%AF%95%E8%BE%85%E5%8A%A9

**Comment by modraedlau** [comment]
非常感谢两位大大的回复，确实只能proxy了，但是我浏览器一直用socket5代理，我另外再写了个http->socket5的实现。我想urllib可否类似[request](https://github.com/request/request)一样支持socket5代理：
```
	agentClass: Agent,
	agentOptions: {
		socksHost: 'my-tor-proxy-host', // Defaults to 'localhost'.
		socksPort: 9050, // Defaults to 1080.

		// Optional credentials
		socksUsername: 'proxyuser',
		socksPassword: 'p@ssw0rd',
	}
```

**Comment by modraedlau** [comment]
非常感谢，此issue可以关闭了
